name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get current date
        id: get_date
        run: echo "DATE_TAG=$(date +'%d_%m_%Y')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t allaboutdevopss/python_frontend:${{ env.DATE_TAG }} .

      - name: Push Docker image
        run: |
          docker push allaboutdevopss/python_frontend:${{ env.DATE_TAG }}
